
name: Build and push Frontend

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths:
      - "frontend/src/BuildNumber.json"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
       name: Set up QEMU
       uses: docker/setup-qemu-action@v1
      -
        name: Build and push frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: <frontend docker>:latest
          file: frontend/Dockerfile
          context: ./frontend
          platforms: linux/amd64,linux/arm/v7
          
